const el = (s)=>document.querySelector(s);const app=el('#app');
const routes={'/home':home,'/portfolio':portfolio,'/autopilot':autopilot,'/execute':execute,'/withdraw':withdraw,'/settings':settings,'/legal':legal};
async function j(p){const r=await fetch(p);return r.json();}
async function home(){app.innerHTML=`<div class="card"><h2>Next Order Plan</h2><div>Balanced 70/30 • $50 Friday • Drift-aware split</div></div><div class="card"><h2>Right Now Tilt</h2><div>Macro stress → +$10 to Safety (VAF/GOLD)</div></div><div class="banner">All providers governed equally · No favorites</div>`;}
async function portfolio(){const u=await j('/assets/universe.json');app.innerHTML=`<div class="card"><h2>Portfolio</h2><div class="grid cols-2"><div><h3>Growth vs Safety</h3><div>Placeholder pie (70/30)</div></div><div><h3>Planned Buys</h3><ul>${u.etfs.map(e=>`<li>${e.symbol} — ${e.sleeve}</li>`).join('')}</ul></div></div></div>`;}
async function autopilot(){const r=await j('/assets/rules.json');const l=await j('/assets/loss_guard.json');const d=await j('/assets/radar.json');app.innerHTML=`<div class="card"><h2>Autopilot</h2><div>Weekly • DCA <b>ON</b> • Radar <b>ON</b></div><hr/><h3>Targets (Balanced)</h3><div>Growth: ${Math.round(r.risk_bands.balanced.growth*100)}% · Safety: ${Math.round(r.risk_bands.balanced.safety*100)}%</div><h3>Guardrails</h3><ul><li>Weekly brake: ${l.weekly_brake_drop_pct}%</li><li>Safety floor: ${Math.round(l.safety_floor*100)}%</li><li>Max growth overweight: ${Math.round(l.max_growth_overweight*100)}%</li></ul><h3>Radar caps</h3><ul><li>Max actions/week: ${d.max_actions_per_week}</li><li>Monthly extra cap: ~$${d.monthly_extra_cap}</li></ul></div>`;}
async function execute(){app.innerHTML=`<div class="card"><h2>Execute</h2><div class="grid cols-2"><button class="btn" onclick="open('https://www.raizinvest.com.au/','_blank')">Raiz</button><button class="btn" onclick="open('https://www.spaceship.com.au/','_blank')">Spaceship</button><button class="btn" onclick="open('https://www.commsec.com.au/','_blank')">CommSec Pocket</button><button class="btn" onclick="open('https://www.stockspot.com.au/','_blank')">Stockspot</button><button class="btn" onclick="open('https://www.quietgrowth.com.au/','_blank')">QuietGrowth</button></div><p><small class='muted'>Execute at your chosen provider. No custody in this app.</small></p></div>`;}
async function withdraw(){app.innerHTML=`<div class="card"><h2>Withdraw</h2><div class="grid cols-2"><input id="amt" class="input" placeholder="Amount (AUD)" /><button class="btn" id="go">Create Sell Plan</button></div><div id="plan" style="margin-top:10px;"></div></div>`;el('#go').onclick=()=>{const v=parseFloat(el('#amt').value||'0');if(!v||v<=0){el('#plan').innerHTML='<small class="muted">Enter a valid amount.</small>';return;}el('#plan').innerHTML='Plan: Sell from safety sleeve first (VAF/GOLD), respecting min trade size.';};}
async function settings(){app.innerHTML=`<div class="card"><h2>Settings</h2><div class="grid cols-2"><div><h3>Risk Band</h3><select class="input"><option>Conservative</option><option selected>Balanced</option><option>Growth</option></select></div><div><h3>Contribution</h3><input class="input" placeholder="$50 / week" /></div></div></div>`;}
async function legal(){app.innerHTML=`<div class="card legal"><h2>Legal</h2><a href="/legal/privacy.html" target="_blank">Privacy Policy</a><a href="/legal/terms.html" target="_blank">Terms of Service</a><a href="/legal/disclaimer.html" target="_blank">General Advice & Risk Disclaimer</a><a href="/legal/about.html" target="_blank">About</a><a href="/legal/contact.html" target="_blank">Contact</a></div>`;}
function route(){const h=location.hash.replace('#','')||'/home';(routes[h]||home)();}
addEventListener('hashchange',route);addEventListener('load',route);
